In [5]:
import numpy as np
print(np.array([2,4,6,8]))

[2 4 6 8]


In [6]:
import numpy as np
n = 5
identity_matrix = np.eye(n)
print("Identity matrix of size", n, ":")
print(identity_matrix)

Identity matrix of size 5 :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [2]:
import random
import numpy as np
x=[]
for row in range(0,3):
    for column in range(0,3):
        if row==column:
            x.append(np.random.randint(0,10))
        else:
            x.append(0)
z=np.array(x)
print(z.reshape(3,3))

[[8 0 0]
 [0 7 0]
 [0 0 3]]


In [10]:
import numpy as np
l1=[2,4,6]
a1=np.array(l1)
print(a1)

[2 4 6]


In [1]:
import numpy as np
import random
n = 3
i= np.eye(n,dtype=int)
a=random.randint(1,10)
p=np.where(i==1,a,i)
print(p)

[[8 0 0]
 [0 8 0]
 [0 0 8]]


In [12]:
import numpy as np
l1=[2,4,6]
a1=np.array(l1)
c=[456,45467,456]
c.append(a1)
print(c)

[456, 45467, 456, array([2, 4, 6])]


In [13]:
import numpy as np
print(np.fromstring('1234',sep=','))

[1234.]


In [14]:
import numpy as np
a1=np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
import numpy as np
a1=np.arange(1,11,2)
print(a1)

[1 3 5 7 9]


In [16]:
import numpy as np
for i in np.arange(1,3):
    for j in np.arange(1,5):
        print(i,j)

1 1
1 2
1 3
1 4
2 1
2 2
2 3
2 4


In [10]:
import numpy as np
a1=np.empty([3,2],dtype=float)
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
import numpy as np
a1=np.zeros([3,2],dtype=float)
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
import numpy as np
a1=np.ones([3,2],dtype=float)
print(a1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
import numpy as np
np.linspace(10,11,5)

array([10.  , 10.25, 10.5 , 10.75, 11.  ])

In [21]:
import numpy as np
x=np.array([2,4,7,4,667])
y=np.copy(x)
print(y)

[  2   4   7   4 667]


In [22]:
import numpy as np
n1=np.arange(1,7)
print(n1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [23]:
import numpy as np
print(np.full(10,6))

[6 6 6 6 6 6 6 6 6 6]


In [24]:
import numpy as np
a1=np.linspace(1,4,4,dtype=int)
b=np.linspace(2,10,4)
print(a1,b)

[1 2 3 4] [ 2.          4.66666667  7.33333333 10.        ]


In [25]:
import numpy
MyList = [1, 2, 3, 4, 5]
arr1=numpy.array(MyList)
print("The ndarray from the list object is  :", arr1, "\n")

The ndarray from the list object is  : [1 2 3 4 5] 



In [26]:
a=0
b=1
l=[a,b]
for i in range(1,11):
    c=a+b
    a=b
    b=c
    l.append(c)
print(l)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [27]:
import numpy as np
import pandas as pd
a=0
l=[a]
for i in range(0,8):
    n=a*a
    l.append(n)
    a=a+1
x=np.array(l)
s=pd.Series(x)
s

0     0
1     0
2     1
3     4
4     9
5    16
6    25
7    36
8    49
dtype: int32

In [16]:
import numpy as np
print(np.empty([3,2],dtype=float))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
import numpy as np
print(np.zeros(5 ,dtype=int))

[0 0 0 0 0]


In [30]:
import numpy
print(numpy.full([2,2],'False'))

[['False' 'False']
 ['False' 'False']]


In [31]:
import numpy as np
print(np.ones([2,4] ,dtype=float))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
import numpy as np
a=np.ones([3,2] ,dtype=float)
print(a[1,:])

[1. 1.]


In [33]:
for x in [20,30]:
    for y in ['a','d']:
        print(x,y)

20 a
20 d
30 a
30 d


In [34]:
import numpy as np
a=0
b=1
l=[a,b]
for i in range(1,9):
    c=a+b
    a=b
    b=c
    l.append(c)
z=np.array(l)
print(z)

[ 0  1  1  2  3  5  8 13 21 34]


In [35]:
import pandas as pd
a=0
b=1
l=[a,b]
for i in range(1,7):
    c=a+b
    a=b
    b=c
    l.append(c)
z=pd.Series(data=l,dtype=float)
z.name='Fibonacci'
print(z)

0     0.0
1     1.0
2     1.0
3     2.0
4     3.0
5     5.0
6     8.0
7    13.0
Name: Fibonacci, dtype: float64


In [36]:
import numpy as np
n1=np.arange(1,7)
n1.reshape(3,2)
print(n1[1:2])

[2]


In [1]:
a=0
list2=[a]
for i in range(0,8):
    num=a*a
    list2.append(num)
    a=a+1
print(list2)

[0, 0, 1, 4, 9, 16, 25, 36, 49]
