In [1]:
import pandas as pd
a1=[32,5,6,54,64,6,74,46,34]
s1=pd.Series(a1)
print(s1)

0    32
1     5
2     6
3    54
4    64
5     6
6    74
7    46
8    34
dtype: int64


In [2]:
import pandas as pd
import numpy as np
a1=np.array([4,2,5,5,67,8,6,4])
s1=pd.Series(a1)
print(s1)

0     4
1     2
2     5
3     5
4    67
5     8
6     6
7     4
dtype: int64


In [3]:
import pandas as pd
a1={1:'Aman',
    2:'Dhiraj',
    3:'Aditya'}
s1=pd.Series(a1)
print(s1)

1      Aman
2    Dhiraj
3    Aditya
dtype: object


In [4]:
import pandas as pd
a1="this is a "
s1=pd.Series(a1)
print(s1)

0    this is a 
dtype: object


In [5]:
import pandas as pd
a1=[32,5,6,54,64,6,74,46,34]
s1=pd.Series(data=a1,dtype=float)
print(s1)

0    32.0
1     5.0
2     6.0
3    54.0
4    64.0
5     6.0
6    74.0
7    46.0
8    34.0
dtype: float64


In [6]:
import pandas as pd
a1=[32,5,6,54,64,6,74,46,34]
s1=pd.Series(data=a1,index=[2,43,3,452,45,5442,53,25,54],dtype=float)
print(s1)

2       32.0
43       5.0
3        6.0
452     54.0
45      64.0
5442     6.0
53      74.0
25      46.0
54      34.0
dtype: float64


In [7]:
import pandas as pd
a1=[32,5,6,54,64,6,74,46,34]
s1=pd.Series(data=a1,dtype=float)
a=s1.values
print(a)

[32.  5.  6. 54. 64.  6. 74. 46. 34.]


In [8]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
SERIES2=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(SERIES2)

The SERIES from the Scalar Value is :
0    100
1    200
2    300
3    400
4    500
dtype: int64


In [9]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[3])

The SERIES from the Scalar Value is :
400


In [10]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[1])

The SERIES from the Scalar Value is :
200


In [51]:
import pandas
scalarvalue=[100,200,300,400,100]
print("The Scalar Value List is = ", scalarvalue)
S1=pandas.Series(scalarvalue, index=['1st', '2nd', '3rd', '4th','5th'])
print(S1[-2])

The Scalar Value List is =  [100, 200, 300, 400, 100]
400


C:\Users\DELL\AppData\Local\Temp\ipykernel_22876\2437208951.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(S1[-2])


In [12]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[1:])

The SERIES from the Scalar Value is :
1    200
2    300
3    400
4    500
dtype: int64


In [13]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[1:3])

The SERIES from the Scalar Value is :
1    200
2    300
dtype: int64


In [14]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[-4:])

The SERIES from the Scalar Value is :
1    200
2    300
3    400
4    500
dtype: int64


In [15]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[-2:-4])

The SERIES from the Scalar Value is :
Series([], dtype: int64)


In [16]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[-4:-2])

The SERIES from the Scalar Value is :
1    200
2    300
dtype: int64


In [17]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[1:-4])

The SERIES from the Scalar Value is :
Series([], dtype: int64)


In [18]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[4:-2])

The SERIES from the Scalar Value is :
Series([], dtype: int64)


In [19]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[-2:4])

The SERIES from the Scalar Value is :
3    400
dtype: int64


In [20]:
import pandas
scalarvalue=[100, 200, 300, 400, 500]
s1=pandas.Series(scalarvalue)
print("The SERIES from the Scalar Value is :")
print(s1[-4:2])

The SERIES from the Scalar Value is :
1    200
dtype: int64


In [21]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
print("The Scalar Value List is       = ", scalarvalue)
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1

The Scalar Value List is       =  [100, 200, 300, 400, 100]


A    100
B    200
C    300
D    400
E    100
dtype: int64

In [22]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.name='Scalar series'
print(S1)

A    100
B    200
C    300
D    400
E    100
Name: Scalar series, dtype: int64


In [23]:
import pandas as pa
diction2 = {
                     "Brand": "Ford",
                     "Model": "Mustang",
                     "Year": 1964
            }
MyS=pa.Series(diction2)
MyS.name = 'Mustang is in'
print(MyS) 


Brand       Ford
Model    Mustang
Year        1964
Name: Mustang is in, dtype: object


In [24]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1)

Scalar series
A    100
B    200
C    300
D    400
E    100
dtype: int64


In [25]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.values

array([100, 200, 300, 400, 100])

In [26]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.size)

5


In [27]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.empty)

False


In [28]:
import pandas as pa
diction2 = {
                     "Brand": "Ford",
                     "Model": "Mustang",
                     "Year": 1964
            }
MyS=pa.Series(diction2)
print(MyS.loc['Year'])


1964


In [29]:
import pandas as pa
diction2 = {
                     "Brand": "Ford",
                     "Model": "Mustang",
                     "Year": 1964
            }
MyS=pa.Series(diction2)
print(MyS.iloc[1])


Mustang


In [30]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.count())

5


In [31]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.head(2))

Scalar series
A    100
B    200
dtype: int64


In [32]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.tail(2))

Scalar series
D    400
E    100
dtype: int64


In [33]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.head(-3))

Scalar series
A    100
B    200
dtype: int64


In [34]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.tail(-3))

Scalar series
D    400
E    100
dtype: int64


In [35]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(S1.sort_values(ascending=False))

Scalar series
D    400
C    300
B    200
A    100
E    100
dtype: int64


In [36]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.index.name='Scalar series'
print(type(S1))

<class 'pandas.core.series.Series'>


In [37]:
import pandas 
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
import pandas 
scalarvalue2=[200, -300, -600,-100,700]
S2=pandas.Series(scalarvalue2)
s3=S1+S2
print(s3)

0    300.9
1   -100.0
2   -900.8
3   -500.0
4    800.5
dtype: float64


In [38]:
import pandas 
scalarvalue3=[200, -100.9, -300.4, 300, 400]
S3=pandas.Series(scalarvalue3, index=[3, 4, 5, 6, 7])
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
s3=S1+S3
print(s3)

0      NaN
1      NaN
2      NaN
3   -200.0
4     -0.4
5      NaN
6      NaN
7      NaN
dtype: float64


In [39]:
import pandas 
scalarvalue3=[200, -100.9, -300.4, 300, 400]
S3=pandas.Series(scalarvalue3, index=[3, 4, 5, 6, 7])
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
s3=S1-S3
print(s3)

0      NaN
1      NaN
2      NaN
3   -600.0
4    201.4
5      NaN
6      NaN
7      NaN
dtype: float64


In [40]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([7,2,8,4,5])
a=np.where(x==y)
print(x[a])

[2 4 5]


In [41]:
import pandas 
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
import pandas 
scalarvalue2=[200, -300, -600,-100,700]
S2=pandas.Series(scalarvalue2)
s3=S1[2]+S2[4]
print(s3)

399.2


In [42]:
import pandas 
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
import pandas 
scalarvalue2=[200, -300, -600,-100,700]
S2=pandas.Series(scalarvalue2)
s3=S1[2:]+S2[-3:]
print(s3)

2   -900.8
3   -500.0
4    800.5
dtype: float64


In [43]:
import pandas 
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
import pandas 
scalarvalue2=[200, -300, -600,-100,700]
S2=pandas.Series(scalarvalue2)
s3=S1.add(S2)
s3

0    300.9
1   -100.0
2   -900.8
3   -500.0
4    800.5
dtype: float64

In [44]:
import pandas as pd
a=pd.Series(['Ha','dsf'],index=['fg','er'])
a

fg     Ha
er    dsf
dtype: object

In [45]:
import pandas
a=pandas.Series([10,20,30,40,50])
a[-2:4]

3    40
dtype: int64

In [46]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.sort_values()

A    100
E    100
B    200
C    300
D    400
dtype: int64

In [47]:
import pandas 
scalarvalue=[100, 200, 300, 400, 100]
S1=pandas.Series(scalarvalue, index=pandas.Index( ['A','B','C','D','E'] ) )
S1.sort_values(ascending=False)

D    400
C    300
B    200
A    100
E    100
dtype: int64

In [48]:
import pandas as pd
a=pd.Series(data=['a','e','i','o','u'])
a.name='Vowels'
a.index=[1,2,3,4,5]
a

1    a
2    e
3    i
4    o
5    u
Name: Vowels, dtype: object

In [49]:
import pandas as pd
a=pd.Series(data=['a','e','i','o','u'])
a.name='Vowels'
a.index=[1,2,3,4,5]
a[-2:4]

4    o
Name: Vowels, dtype: object

In [50]:
import pandas 
scalarvalue3=[200, -100.9, -300.4, 300, 400]
S3=pandas.Series(scalarvalue3, index=[3, 4, 5, 6, 7])
scalarvalue=[100.9, 200.0, -300.8, -400.0, 100.5]
S1=pandas.Series(scalarvalue)
S1.add(S3,fill_value=8)

0    108.9
1    208.0
2   -292.8
3   -200.0
4     -0.4
5   -292.4
6    308.0
7    408.0
dtype: float64